---

- name: "Get Sonar repo"
  yum_repository: 
    name: sonar
    description: Sonar RedHat repo
    baseurl: http://downloads.sourceforge.net/project/sonar-pkg/rpm
    gpgcheck: no

- name: "Download Sonar"
  yum: name=sonar state=present
  
- name: "Start Sonar"
  service: name=sonar state=started enabled=yes