---

- hosts: all
  become: true
  tasks:
    - include: assertions.yml 
    - include: java.yml

- hosts: ci
  become: true
  # TODO: Install maven 3 and add it to PATH
  roles:
    - jenkins

- hosts: repository
  become: true
  roles:
    - nexus

- hosts: quality
  become: true
  roles:
    - sonar