---

- name: "Create user"
  user: name="nexus" state="present"

- name: "Grab Nexus"
  get_url: url="http://download.sonatype.com/nexus/3/latest-unix.tar.gz" dest="/tmp/nexus.tar.gz"
  when: "ansible_local.nexus_installed == false"

- name: "Unarchive Nexus"
  unarchive: src="/tmp/nexus.tar.gz" dest="/opt" copy="no"
  when: "ansible_local.nexus_installed == false"

- name: "Find Nexus version"
  shell: "find /opt -maxdepth 1 -type d -name 'nexus-*'"
  register: nexus_path
  changed_when: False
  
- name: "Set nexus as Nexus folder's owner"
  file: path="{{ nexus_path.stdout }}" owner=nexus group=nexus recurse=yes state=directory

- name: "Create nexus symlink"
  file: src="{{ nexus_path.stdout }}" dest="/opt/nexus" state="link"

- name: "Install service"
  template: src="{{ role_path }}/templates/nexus.service.j2" dest="/usr/lib/systemd/system/nexus.service"

- name: "Enable service"
  systemd: name=nexus state=started daemon_reload=yes